### ISSUE TITLE
[Backend] Decide on a backend technology

### ISSUE THREAD

**Issue by lindlands** [Green-Kittens/bathroom-finder#35]
Previous ideas from Jonas: Express.js(backend), Rest API with Mongodb as database.

**Comment by dylantompkins** [comment]
From kayla in slack:

> Hey guys, I can't make it to class today because I woke up with a runny nose and sore throat.
Here is my notes on backend technologies:
MERN Stack is popular: MongoDB as a database, Express.js as framework, React (React-Native) as a library for frontend, and Node.js as backend platform
Good for small teams
Cheap and fast
The only con found was that MongoDB can be particular
Node.js – with TypeScript
Clear and flexible language
Can allow large-scale mobile apps
Already familiar with from class
Using TypeScript for frontend; so should parallel and use for backend as well
Express and Meteor works with Node.js
Express
Focused more on web applications
Not specifically for mobile applications
Can still work with React-Native to build mobile application
Very popular – well documented
Very popular to use with Node.js
Already some experience from class
Meteor
Markets itself as “all-in-one” JavaScript framework
Works for mobile, desktop, and web apps
Frontend and backend
Less (popular) documentation than Express
!!I reccomend we use Node.js with Express.js!!
https://www.toptal.com/nodejs/nodejs-frameworks-comparison
https://ninetailed.io/blog/best-javascript-frameworks/
https://nodejs.org/en/learn/getting-started/nodejs-with-typescript
https://betterstack.com/community/guides/scaling-nodejs/nodejs-typescript/ (edited)
