### ISSUE TITLE
[Backend] Decide on APIs for P0 tasks

### ISSUE THREAD

**Issue by lindlands** [Green-Kittens/bathroom-finder#38]

**Comment by dylantompkins** [comment]
| API Endpoint       | /bathrooms                       |
| ------------------ | -------------------------------- |
| Description        | Retrieve a list of all bathrooms |
| Request Method     | GET                              |
| Request Parameters | none                             |
| Response Format    | list of Bathroom objects         |
| Errors             | 500 (server error)               |

| API Endpoint       | /bathrooms/{bathroomID}                     |
| ------------------ | ------------------------------------------- |
| Description        | Retrieve information on a specific bathroom |
| Request Method     | GET                                         |
| Request Parameters | `bathroomID`                                |
| Response Format    | a single Bathroom object                    |
| Errors             | 404 (ID does not exist), 500 (server error) |

| API Endpoint       | /bathrooms                                                                |
| ------------------ | ------------------------------------------------------------------------- |
| Description        | Create a new bathroom                                                     |
| Request Method     | POST                                                                      |
| Request Parameters | a single bathroom object (without ID or other things computed by backend) |
| Response Format    | the same bathroom object (as stored in the backend)                       |
| Errors             | 201 (Created), 400 (Bad Request), 500 (server error)                      |

| API Endpoint       | /bathrooms/{bathroomID}/reviews              |
| ------------------ | -------------------------------------------- |
| Description        | Retrieve the ratings for a specific bathroom |
| Request Method     | GET                                          |
| Request Parameters | `bathroomID`                                 |
| Response Format    | list of review objects                       |
| Errors             | 500 (server error)                           |

| API Endpoint       | /bathrooms/{bathroomID}/reviews                           |
| ------------------ | --------------------------------------------------------- |
| Description        | Submit a new review for a given bathroom                  |
| Request Method     | POST                                                      |
| Request Parameters | `bathroomID` and Review object                            |
| Response Format    | the review object as stored in the backend (with ID, etc) |
| Errors             | 201 (Created), 400 (Bad Request), 500 (server error)      |

| API Endpoint       | /bathrooms/{bathroomID}/tags                        |
| ------------------ | --------------------------------------------------- |
| Description        | Retrieve all tags currently applied to the bathroom |
| Request Method     | GET                                                 |
| Request Parameters | `bathroomID`                                        |
| Response Format    | a list of strings                                   |
| Errors             | 500 (server error)                                  |

| API Endpoint       | /bathrooms/{bathroomID}/tags                         |
| ------------------ | ---------------------------------------------------- |
| Description        | Submit a new revision of the list of tags            |
| Request Method     | POST                                                 |
| Request Parameters | `bathroomID` and a list of strings                   |
| Response Format    | the list of strings                                  |
| Errors             | 201 (Created), 400 (Bad Request), 500 (server error) |

**Comment by dylantompkins** [comment]
Reviewed with team in person
