### ISSUE TITLE
[Frontend] Decide on a UI Style

### ISSUE THREAD

**Issue by lindlands** [Green-Kittens/bathroom-finder#42]

**Comment by dylantompkins** [comment]
![Image](https://github.com/Green-Kittens/bathroom-finder/assets/36244177/232318de-5a8f-4072-8d83-d0e5cee15eb3)

![Image](https://github.com/Green-Kittens/bathroom-finder/assets/36244177/6849e98c-d7ec-4a7a-a332-0e6e2992068a)

presented in class, moving forward with implementation
