### ISSUE TITLE
Sprint Review Presentation

### ISSUE THREAD

**Issue by dltompki** [Green-Kittens/bathroom-finder#48]
See [sprint-2-review-reqs.pdf](https://github.com/Green-Kittens/bathroom-finder/files/14475930/sprint-2-review-reqs.pdf) for requirements for the presentation.

Please post links to powerpoint and excel as they are created here so we can have easy access.

**Comment by kaylantran** [comment]
Presentation: https://cpslo.sharepoint.com/:p:/r/sites/csc308group6/Shared%20Documents/Sprint%20%232.pptx?d=w9af0acb673054d6f8c0aa58907182fb2&csf=1&web=1&e=VknNGW
Excel for Metrics: https://cpslo.sharepoint.com/:x:/r/sites/csc308group6/Shared%20Documents/metrics%20sprints.xlsx?d=w7d1b5d025e9a4e6ea18bffcc0275ed87&csf=1&web=1&e=pHs5P7
