### ISSUE TITLE
[REQ] update tech spec

### ISSUE THREAD

**Issue by dltompki** [Green-Kittens/bathroom-finder#79]
- [ ] update tech spec from CSC 308 according to current state of solution
    - [x] Requirement changes and design modifications if applicable
      - [x] requirements
      - [x] user stories
      - [x] design section
    - [x] data schema changes
    - [x] tests
  - [ ] enumerate changes in new section at the top called "Updates From Previous
        Version"

**Comment by dltompki** [comment]
https://cpslo.sharepoint.com/:w:/r/sites/csc308group6/Shared%20Documents/Tech%20Spec.docx?d=wf484971ab0e54ccc91a6859806eddf55&csf=1&web=1&e=jW3K6Z

**Comment by kaylantran** [comment]
spent 1 hour updating tech spec
